CREATE TABLE card
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250) NOT NULL DEFAULT '' COMMENTS ''
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE tag
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(250) NOT NULL DEFAULT '' COMMENTS ''
) CHARACTER SET utf8
  COLLATE utf8_general_ci;