spring:
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3308/primary"
    username: grissom
    password: grissom
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6566
    lettuce:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 3
        max-wait: -1
      shutdown-timeout: 2000
    timeout: 3000
  redis-cached:
    host: 127.0.0.1
    port: 6566
    lettuce:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 3
        max-wait: -1
      shutdown-timeout: 2000
    timeout: 3000
  redis-stored:
    host: 127.0.0.1
    port: 6567
    lettuce:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 3
        max-wait: -1
      shutdown-timeout: 2000
    timeout: 3000
  cache:
    type: redis
resilience4j:
  retry:
    retry-aspect-order: 2   # 서킷 이후 Retry
    instances:
      externalAuthApiRetry:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
  #        ignore-exceptions:
  #          - com........// Exception
  circuitbreaker:
    circuit-breaker-aspect-order: 1 # 서킷 먼저
    instances:
      externalAuthApiCircuitBreaker:
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 10 # 10%
